"""empty message

Revision ID: 183cc522f7a3
Revises: 
Create Date: 2023-09-21 16:45:51.343709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183cc522f7a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apod_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_id', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('firebase_uid')
    )
    op.create_table('favorite_article',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('apod_article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apod_article_id'], ['apod_article.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disliked_post',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('disliked_post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disliked_post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_link', sa.String(length=256), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liked_post',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('liked_post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['liked_post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liked_post')
    op.drop_table('image')
    op.drop_table('disliked_post')
    op.drop_table('comment')
    op.drop_table('post')
    op.drop_table('favorite_article')
    op.drop_table('user')
    op.drop_table('apod_article')
    # ### end Alembic commands ###
